# run with CMD + Option + R

###

GET http://localhost:3000/create-image
content-type: application/json

{
    "prompt": "Two animals look at each other with curiosity. 50ies comic black and white style.",
    "pixel": 256,
    "number": 1
}

###

GET http://localhost:3000/complete-text
content-type: application/json

{
    "prompt": "A story about a fish learing to walk"
}